spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
mysql:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
security:
  public-key:
      location: keys/public.pem
  private-key:
      location: keys/key.pem
