spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: backend
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQLDialect

mysql:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

security:
  public-key:
      location: keys/public.pem
  private-key:
      location: keys/key.pem
  access-key-expire-time: 3600
  refresh-key-expire-time: 36000
  token-issuer: yam.com
  default-admin-password: ${DEFAULT_ADMIN_PASSWORD}
